### PR TITLE
fix(staking): align min self delegation with min delegation

### LINKED ISSUE #213: createValidator always fail at CL side
createValidator always fail at CL side even though EL side passed.

CL error message: <br>24-10-16 21:38:39.859 ERRO Failed to process create validator       err="create validator: validator's minimum self delegation must be greater than or equal to minimum delegation" stacktrace="\[errors.go:39 validator.go:124 keeper.go:140 msg_server.go:112 tx.pb.go:290 msg_service_router.go:175 tx.pb.go:292 msg_service_router.go:198 baseapp.go:1015 baseapp.go:953 baseapp.go:762 abci.go:790 abci.go:884 cmt_abci.go:44 abci.go:95 local_client.go:185 app_conn.go:104 execution.go:224 execution.go:202 state.go:1772 state.go:1682 state.go:1617 state.go:1655 state.go:2335 state.go:2067 state.go:929 state.go:836 asm_amd64.s:1695\]"

### PR DESCRIPTION
**Pull request by gezerui0124**
use min_delegation as min_self_delegation to create validator

issue: closes #213

### CODE REVIEW

File: client/x/evmstaking/keeper/validator.go [hunk 1]
```diff
@@ -78,53 +78,57 @@ func (k Keeper) ProcessCreateValidator(ctx context.Context, ev *bindings.IPToken
...
-
-		_, err = skeeperMsgServer.CreateValidator(ctx, msg)
-		if err != nil {
-			return errors.Wrap(err, "create validator")
-		}
+		return errors.Wrap(err, "get validator")
+	}
+
+	moniker := ev.Moniker
+	if moniker == "validator" {
```
Comment (LeoHChen) [inline client/x/evmstaking/keeper/validator.go:90]: what does it mean?  can you add some comments here?

File: client/x/evmstaking/keeper/validator.go [hunk 2]
```diff
@@ -78,53 +78,57 @@ func (k Keeper) ProcessCreateValidator(ctx context.Context, ev *bindings.IPToken
...
+	}
+
+	// Validator does not exist, create validator with self-delegation.
+	msg, err := stypes.NewMsgCreateValidator(
+		validatorAddr.String(),
+		validatorPubkey,
+		amountCoin,
+		stypes.Description{Moniker: moniker},
+		stypes.NewCommissionRates(
+			// Divide these decimals by 100 to convert from basis points to decimal. Will cut off decimal as the rates are integers.
```
Comment (LeoHChen) [inline client/x/evmstaking/keeper/validator.go:116]: commission rate is not integer

File: client/x/evmstaking/keeper/validator.go (hunk 1 above)
Comment (edisonz0718) [inline client/x/evmstaking/keeper/validator.go:90]: I think we should change to  moniker == "" here

**Review by edisonz0718 — APPROVED** [review]

**Review by limengformal — APPROVED** [review]
